### ISSUE TITLE
[Bug report] ARM not supported

### ISSUE THREAD

**Issue by julianfairfax** [39aldo39/libdecsync-bindings-python3#1]
Would be nice if the python module support ARM for the PinePhone and other ARM devices.

**Comment by julianfairfax** [comment]
Would you happen to have a timeline for that addition? I'm excited to get this amazing tool you've made working on my PinePhone!

**Comment by 39aldo39** [comment]
The latest version does have the addition!

**Comment by julianfairfax** [comment]
Thank you!

**Comment by julianfairfax** [comment]
@39aldo39 The pip package hasn't been updated yet so I still can't use this.

**Comment by 39aldo39** [comment]
It is, though? Executing `pip3 install -U libdecsync` should install version 2.1.0. Maybe you thought about `radicale_storage_decsync`?

**Comment by julianfairfax** [comment]
Yes, that's the one I'm trying to use. I get this error when running it:
```
[2021-10-06 18:58:56 +0200] [50589] [CRITICAL] An exception occurred during server startup: Failed to load storage module 'radicale_storage_decsync': libdecsync: Machine type 'aarch64' not supported
```

**Comment by 39aldo39** [comment]
It looks like I don't detect ARM devices correctly. If you are willing to change the source, you could try modifying line 38 from `elif machine_type.startswith("arm"):` to `elif machine_type.startswith("arm") or machine_type == "aarch64":`. I will later correct the detection.

**Comment by julianfairfax** [comment]
I tried installing the AUR package and got this error for libdecsync:
```
==> Starting build()...
Makefile:17: *** Unsupported platform aarch64.  Stop.
==> Entering fakeroot environment...
==> Starting package()...
Makefile:17: *** Unsupported platform aarch64.  Stop.
==> ERROR: A failure occurred in package().
    Aborting...
error making: libdecsync
```

**Comment by 39aldo39** [comment]
The latest version of the bindings should now detect your device correctly, so executing `pip3 install -U libdecsync` should work now.

**Comment by julianfairfax** [comment]
It works!

**Comment by julianfairfax** [comment]
> I tried installing the AUR package and got this error for libdecsync:
> 
> ```
> ==> Starting build()...
> Makefile:17: *** Unsupported platform aarch64.  Stop.
> ==> Entering fakeroot environment...
> ==> Starting package()...
> Makefile:17: *** Unsupported platform aarch64.  Stop.
> ==> ERROR: A failure occurred in package().
>     Aborting...
> error making: libdecsync
> ```

If you create a new release for libdecsync then I can flag the AUR package as out of date. Looking forward to that!
